export interface ApplicationDoc extends Document {
    firstName: string;   
    lastName: string;
    nationalId: string;
    email: string;
    applicantId: string;
    managerId: string | string[] | undefined;
    phone: string;
    dateOfBirth: Date;
    gender: "Male" | "Female" | "Other";
    maritalStatus: "Single" | "Married" | "Divorced" | "Widowed";
    numberOfDependencies: number;
    workSchool: string;
    position: string;
    managerComment: string;
    comment: string;
    suggestedRepaymentPeriod: number;
    suggestedRepaymentPerMonth: number;
    monthlySalary: number;
    amountToPayPerMonth: number;
    amountRequested: number;
    repaymentPeriod: number;
    repaymentPerMonth: number;
    bankAccountNumber: string;
    proofOfEmployment: string;
    copyOfNationalId: string;
    loanStatus: "Pending" | "Update required" | "Approved" | "Rejected";
};
export interface ExistingApplicationDoc extends ApplicationDoc {
    _id: string | {};   
};